name: Build snbt json converter and upload

on:
  push:
    paths:
      - 'snbt_json_converter/**'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3'
          
      - name: Install dependencies (Windows)
        run: |
          pip install pyinstaller
          pip install -r snbt_json_converter/requirements.txt

      - name: Build with PyInstaller (Windows)
        run: |
          python -m PyInstaller -F -n snbt-json-converter-Windows snbt_json_converter/main.py

      - name: Upload (Windows)
        uses: actions/upload-artifact@v4
        with:
          path: dist/snbt-json-converter-Windows.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3'

      - name: Install dependencies (macOS)
        run: |
          pip install pyinstaller
          pip install -r snbt_json_converter/requirements.txt
        
      - name: Build with PyInstaller (macOS)
        run: |
          python -m PyInstaller -F -n snbt-json-converter-macOS snbt_json_converter/main.py

      - name: Upload (macOS)
        uses: actions/upload-artifact@v4
        with:
          name: snbt-json-converter-macOS
          path: dist/snbt-json-converter-macOS

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3'
          
      - name: Install dependencies (Linux)
        run: |
          pip install pyinstaller
          pip install -r snbt_json_converter/requirements.txt

      - name: Build with PyInstaller (Linux)
        run: |
          python -m PyInstaller -F -n snbt-json-converter-Linux snbt_json_converter/main.py

      - name: Upload (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: snbt-json-converter-Linux
          path: dist/snbt-json-converter-Linux
