name: Build FTBQ Color Check and Upload

on:
  push:
    paths:
      - 'ftbq_color_check/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            artifact_name: FTBQ-Color-Check-Windows
            extension: .exe
          - os: macos-latest
            artifact_name: FTBQ-Color-Check-macOS
            extension: 
          - os: ubuntu-latest
            artifact_name: FTBQ-Color-Check-Linux
            extension: 

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r ftbq_color_check/requirements.txt

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller -F -w -n ${{ matrix.artifact_name }} ftbq_color_check/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.artifact_name }}${{ matrix.extension }}
